---
# tasks file for zabbix5-agent
# Add Zabbix Repo
- name: Check Zabbix Agent
  yum:
    name: zabbix22
    state: absent
  register: package_status
- name: Add repository
  yum_repository:
    name: Zabbix
    description: Zabbix YUM repo
    baseurl: https://repo.zabbix.com/zabbix/5.0/rhel/{{ ansible_distribution_major_version }}/$basearch/
- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
- name: Install Zabbix Agent
  yum:
    name: zabbix-agent
    state: installed
- name: Copy Zabbix Configuration
  template:
     src: templates/zabbix_agentd.j2
     dest: /etc/zabbix/zabbix_agentd.conf
     owner: root
     group: root
     mode: 0644
- name: Enable Zabbix Agent
  systemd:
    name: zabbix-agent  
    state: restarted
    enabled: yes
  when: ansible_distribution_major_version >= '7'
- name: Enable Zabbix Agent
  service:
    name: zabbix-agent  
    state: restarted
    enabled: yes
  when: ansible_distribution_major_version <= '6'
