---
# tasks file for zabbix5-agent
# roles/example/tasks/main.yml
- name: Install for SUSE
  import_tasks: suse.yml
  when: ansible_os_family == 'Suse'
- name: Install for RHEL
  import_tasks: rhel.yml
  when: ansible_os_family == 'RedHat'
#- name: Install for Win
#  import_tasks: win.yml
#  when: ansible_os_family == 'Windows'
